### ISSUE TITLE
这段代码写的有问题

### ISSUE THREAD

**Issue by bingdu0** [KunMinX/UnPeek-LiveData#22]
public UnPeekLiveData<T> create() {
      UnPeekLiveData<T> liveData = new UnPeekLiveData<>();
      liveData.isAllowNullValue = this.isAllowNullValue;
      return liveData;
    }
    
UnPeekLiveData 没有这个isAllowNullValue  变量。

**Comment by KunMinX** [comment]
这是父类的变量。
