### ISSUE TITLE
其实根本没有所谓的数据倒灌, 我这里想做一个解释

### ISSUE THREAD

**Issue by xiaojinzi123** [KunMinX/UnPeek-LiveData#26]
### 描述问题

我是一个 MVVM 架构和响应式编程深度使用的一个开发者. Github 上刷到你的这个仓库. 我还是想对你们所说的数据倒灌进行解释说明一下. 

你所说的数据倒灌其实根本不是一个问题或者 bug. 
LiveData 设计就是如此. 接受最近一个信号. 对应流的 Behavior 模式. 
我们有知名度一点的流的实现有 RxJava 和 Kotlin 的 Flow. 在他们的实现中, 分别对应 BehaviorSubject 和 StateFlow
他们的图示如下, 你们可以看到, 在不同的时间点发生订阅, 你总是能收到最近的一个信号. 除非一开始就没发射过信号. 而 LiveData 正是类似于此种模式. 所以你们说它的数据倒灌, 其实根本不是问题, 人家设计本是如此. 
<img src="https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators/S.BehaviorSubject.png" width="500" />

那你们说的数据倒灌根本原因是因为什么呢?
其实是因为你们监听了 Behavior 模式的流或者 LiveData 去做了相应的操作. 
比如你监听一个 LiveData 去做了网络请求
当你界面第一次进入, LiveData 中产生了一个信号, 你收到之后做了一次请求, 后来由于系统配置更改引起界面重建, 但是 ViewModel 还是原先那个, 所以在界面重建后你去监听 LiveData, 就会立马收到一个信号, 导致你又做了一次请求. 
这里说明的场景, 是由于错误使用了 LiveData 引起的. 如果你要监听一个信号做一定的行为, 这类通常是需要监听 Publish 模式的流. 而 LiveData 设计之初就是 Behavior 模式, Publish 模式的行为示意图如下, 你只能收到你订阅点之后的信号. 
<img src="https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators/PublishSubject.png" width="800" />

### 总结

- Behavior 模式可选的方案
  - RxJava 的 BehaviorSubject
  - Kotlin Flow 的 StateFlow
  - LiveData
- Publish 模式可选的方案
  - RxJava 的 PublishSubject
  - Kotlin Flow 的 SharedFlow
  - 我们自定义的 Listener 等

综上所述, 在响应式编程中, 由于你接受的信号源有不同的模式实现. 所以在平常的业务需求中, 我们也要合理的进行选择.

比如我们用于显示界面的场景, Behavior 模式是最适合不过了, 这也是为什么 LiveData 出现的原因. 本就为了显示页面的数据去的. 在界面重建也能重新进行显示.

再比如我们用于执行某些行为的场景, 比如你收到一个信号进行一次网络请求、数据库操作、跳转等等. 这些其实都是需要使用 Publish 模式的.

希望我在这里的长篇大论, 能很好的解释你们出现的所谓的数据倒灌的问题. 在项目中能合理的选择对应的实现去解决问题. 并且对一个响应式的数据源进行监听的时候, 需要先知道它的实现模式是 Behavior 还是 Publish, 以便于你做出判断, 可以用作哪些场景的使用

**Comment by KunMinX** [comment]
我喜欢实事求是的交流，实事求是，意味着扎根于客观实际，基于第一性原理，将实际的背景缕清和找到最优解。

好比，马斯克造火箭，首先追根溯源背景，将实际的背景缕清，最终能推导出综合成本最低、性价比最高的解决方案。

数据倒灌提出的背景，是 2017~2019 年，针对和解决的是，官方提出的 “SharedViewModel + LiveData 完成页面间通信” 方案存在的不足，

那时并没有 stateFlow 等工具，官方建议 “SharedViewModel + LiveData 完成页面间通信”，同样也是基于实际的考虑：

1.满足生命周期安全

2.满足多观察者分发

3.能满足鉴权的结构设计

4.相比 rxjava 足够轻量

显然 LiveData 是满足这些要求的最优解，对 LiveData 进行针对性的改造，使其在特定场景下能满足需求即可。

**Comment by xiaojinzi123** [comment]
1. 我并不是在找你麻烦, 就是客观的讨论
2. RxJava 的 Behavior Subject 和 Publish Subject 很早就已经有了. 比 LiveData 出现的早多了.
3. LiveData 你们对他进行改造, 支持 Publish 的模式, 其实没有什么问题. 我只是觉得 LiveData 的出现本就是 Behavior 模式的一个实现. 如果对它进行改造，我觉得会让人对 LiveData 的印象会越来越模糊. 毕竟响应式真的熟练掌握的还是少数.
4. 当然了对 LiveData 改造支持了 Publish 模式, 比 RxJava 的 Publish Subject 明显的好处就是, LiveData 的创建和销毁系统会帮你做. 这确实是一个好处.

**Comment by xiong0320** [comment]
楼主是将简单问题复杂化，强行灌输什么数据倒灌，出现这个问题根因只是使用共享viewmodel和livedata，退出清空数据就解决的问题搞得这么神乎其神，写的livedata叫"非粘性"livedata就可以了，在这迷惑人

**Comment by Arisono** [comment]
理解而非盲从：先理解 LiveData 的设计意图（状态持有），再决定是否改造

分场景选择：
UI 状态管理 → LiveData 或 StateFlow
一次性事件 → Event Wrapper 或 SharedFlow
领域层数据流 → Flow 或 RxJava
渐进式演进：不要为了“先进”而过度设计，简单场景用 LiveData 仍是最佳选择

原文观点有其项目背景的合理性，但将其表述为 LiveData 的“缺陷”和“必须改造”是过度的。LiveData 的“倒灌”特性在状态管理中反而是优势（确保UI始终有最新状态），只是在事件分发场景下需要额外处理。

<img width="878" height="827" alt="Image" src="https://github.com/user-attachments/assets/e86f3c9f-1c85-4c93-8666-f29a374e3c87" />

**Comment by xiong0320** [comment]
邮件已收到，谢谢！copyright 熊菲苇

**Comment by Arisono** [comment]
> * 我并不是在找你麻烦, 就是客观的讨论
> * RxJava 的 Behavior Subject 和 Publish Subject 很早就已经有了. 比 LiveData 出现的早多了.
> * LiveData 你们对他进行改造, 支持 Publish 的模式, 其实没有什么问题. 我只是觉得 LiveData 的出现本就是 Behavior 模式的一个实现. 如果对它进行改造，我觉得会让人对 LiveData 的印象会越来越模糊. 毕竟响应式真的熟练掌握的还是少数.

我支持你的解释，你的解释非常详细合理，你的解释才是符合设计者官方本来的初衷。
