### ISSUE TITLE
UnPeekLiveData能否读写分离

### ISSUE THREAD

**Issue by qiushui95** [KunMinX/UnPeek-LiveData#3]
只能在ViewModel中写数据。
```
private val _phoneInput: MutableLiveData<String>
```
```
val phoneInput: LiveData<String>
        get() = _phoneInput
```

外部只能拿到phoneInput，只能observe。
希望UnPeekLiveData也能做相应操作。

**Comment by KunMinX** [comment]
@qiushui95 

这个在 v2.0 版就支持了，在 ViewModel 内部使用 UnPeekLiveData，对外公开父类 ProtectedUnPeekLiveData 即可

**Comment by qiushui95** [comment]
@KunMinX 好的
