### ISSUE TITLE
请问未来支持 Flow 通过 asLiveData 转 LiveData 的场景吗？

### ISSUE THREAD

**Issue by initialjie** [KunMinX/UnPeek-LiveData#30]
目前看应该不支持，是否可以通过让 ProtectedUnPeekLiveData 继承 MediatorLiveData，然后通过 MediatorLiveData.addSource(xxxFlow.asLiveData()) 方式包一层，来转发 ‘Flow 转 LiveData’ 的数据？

**Comment by KunMinX** [comment]
暂无计划。感兴趣可自行 fork 验证想法
