### ISSUE TITLE
DialogFragment中收不到信息

### ISSUE THREAD

**Issue by BaiMingxu** [KunMinX/UnPeek-LiveData#34]
大佬我在Fragment中setValue，为什么在DialogFragment弹窗中收不到信息？

**Comment by KunMinX** [comment]
UnPeekLiveData 设计为新订阅不自动 replay 数据。

弹窗 Observe 时机晚于 fragment setValue 时机，故难接收。

页面通信通常建议向上级传递，例如 dialog set，页面接收，而不是反过来。

如需向 dialog 传初值，建议考虑原生 bundle argument 方式。

**Comment by BaiMingxu** [comment]
好的谢谢您
