### ISSUE TITLE
还是会发生数据倒灌

### ISSUE THREAD

**Issue by zhaoxiuyu** [KunMinX/UnPeek-LiveData#38]
![image](https://github.com/KunMinX/UnPeek-LiveData/assets/16554580/33408243-3f93-40fe-bb90-f1f96f7759f2)

VoicePtaView 是自定义 ConstraintLayout，里面包含多个Fragment。
当VoicePtaView 多次被 removeVIew 并 addVIew时， 就会发生数据倒灌，收到多次回调。

Fragment中
val viewModel by activityViewModels<VoiceViewModel>()

初始化 
    val mTTSLiveData: MutableResult<BaseResponse<List<TTSCloneData>>> =
        MutableResult.Builder<BaseResponse<List<TTSCloneData>>>().setAllowNullValue(true).create()

/// 订阅
viewModel.mTTSCloneListDataLiveData.observe(viewLifecycleOwner){}

**Comment by KunMinX** [comment]
根据你提供的信息，暂无法判断具体造成旧数据回推的原因。可以试试 MVI-Dispatcher 组件来做消息分发。

https://github.com/KunMinX/MVI-Dispatcher-KTX

**Comment by zhaoxiuyu** [comment]
另外，我在调用.clean()方法时报错了
![image](https://github.com/KunMinX/UnPeek-LiveData/assets/16554580/c1d4ffe7-a9dc-48a2-bb1a-151412df3602)
