### ISSUE TITLE
什么时候可以封装个支持多进程的呢,跨进程或者跨App

### ISSUE THREAD

**Issue by Chills719** [KunMinX/UnPeek-LiveData#4]

**Comment by KunMinX** [comment]
@Chills719 

liveData 的职责边界仅限于 进程内页面间的通信，UnPeekLiveData 的职责也仅限于在此基础上限制数据的倒灌问题。

如需跨进程通信，请寻求其他技术的帮助。

**Comment by Chills719** [comment]
好的,谢谢
