### ISSUE TITLE
源码下载不了. 

### ISSUE THREAD

**Issue by Liforent** [KunMinX/UnPeek-LiveData#40]
https://repo.maven.apache.org/maven2/com/kunminx/arch/unpeek-livedata/7.8.0@aar/unpeek-livedata-7.8.0@aar.pom链接打不开,看看是不是配置错了?

**Comment by KunMinX** [comment]
可以看下 jitpack 仓库的  'com.github.KunMinX:UnPeek-LiveData:7.8.0'

maven center 有时不是很好用
