### ISSUE TITLE
后台data返回null，被拦截了，请问怎么处理比较好

### ISSUE THREAD

**Issue by lzy6** [KunMinX/UnPeek-LiveData#5]
排查了下是ProtectedUnPeekLiveData里setValue的if (value != null || isAllowNullValue) {进行的拦截，livedata回调进不去，value是null，我把这个判断注释掉了，会有什么影响么

**Comment by KunMinX** [comment]
@lzy6 
有需要推送 null 值的场景，通过 builder 构造器来实例化 UnPeekLiveData 就好，构造过程中 isAllowNullValue 设置为 true 即可，具体看源码示例
