### ISSUE TITLE
observers默认值为什么是true？

### ISSUE THREAD

**Issue by wlwlxgg** [KunMinX/UnPeek-LiveData#6]
observe时，默认设置为true，这个设计是为什么呢？
考虑Fragment和Activity交互时，Fragment后observe一条数据，此时如果首次observe默认值为true，会导致第一次的数据无法收到。数据倒灌为什么要把第一次observe的数据也屏蔽

**Comment by KunMinX** [comment]
@wlwlxgg 

倒灌的时机就是发生在 “下一次进入” 时的 “第一次”。

如果你想更全面地了解这类问题，只能自己去多多尝试，把各种场景都走一遍，不然光靠别人字面上讲 也很难给你讲明白。

**Comment by wlwlxgg** [comment]
我对「仅适用于 “页面返场回调的场景”」不能赞同。首先LiveData是要先进场，才会出现返场倒灌，不然何来的倒灌

**Comment by wlwlxgg** [comment]
现在您的库，解决了下一次进入时的第一次。但是对第一次进入时，由于默认拦截了。只能等到下一次postValue才能生效

**Comment by wlwlxgg** [comment]
譬如SingleEvent，也是private final AtomicBoolean mPending = new AtomicBoolean(false);
