### ISSUE TITLE
livedata数据倒灌的，设置一个局部变量，消耗掉第一次的observe不就可以了吗？

### ISSUE THREAD

**Issue by zhouzhihao07** [KunMinX/UnPeek-LiveData#9]
![image](https://user-images.githubusercontent.com/8677018/116766668-410dc000-aa5e-11eb-90c0-24233c7952dd.png)

**Comment by KunMinX** [comment]
是的，您真厉害，您是对的，一年其实只有 3 个季节，您说的这种方式应付 3 个季节的情况足够了。

**Comment by zhouzhihao07** [comment]
以上是确定倒灌一定发生的情况下（数据一定变化）才需要消耗第一次，但真实的情况可能是不确定数据什么时候发生，所以我改版了一下

我觉得可以应付这种情况，不知道您说的是不是这季，如果还有其他季，请赐教。

> 是的，您真厉害，您是对的，一年确实只有 3 个季节，您说的这种方式应付 3 个季节的情况足够了。

![QQ图片20210501101442](https://user-images.githubusercontent.com/8677018/116767989-1c1d4b00-aa66-11eb-8238-dba4036ecf14.png)

**Comment by KunMinX** [comment]
多页面多观察者、旋屏重建等等，这些季节的存在，以及兼顾这些季节下的倒灌处理，你想弄明白，只有自己去累积样本、去亲历和体会，不然也很难让人口头讲明白。
